In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')


In [2]:
import pandas as pd

In [3]:
m=pd.read_csv(r'C:\Users\Lenovo\Downloads\Mobile_data.csv',header=0)  # IT IS USED TO ACCESS THE FILE

In [4]:
m.head()

battery_power  clock_speed  fc  int_memory  m_dep  mobile_wt  n_cores  pc  \
0            842          2.2   1           7    0.6        188        2   2   
1           1021          0.5   0          53    0.7        136        3   6   
2            563          0.5   2          41    0.9        145        5   6   
3            615          2.5   0          10    0.8        131        6   9   
4           1821          1.2  13          44    0.6        141        2  14   

   px_height  px_width   ram  sc_h  sc_w  talk_time  price_range  
0         20       756  2549     9     7         19            1  
1        905      1988  2631    17     3          7            2  
2       1263      1716  2603    11     2          9            2  
3       1216      1786  2769    16     8         11            2  
4       1208      1212  1411     8     2         15            1

In [5]:
m.shape   # it tells about how many rows and columns are present

(2000, 15)

In [6]:
m.describe()   # describe method tells about the statistics value of the data

battery_power  clock_speed           fc   int_memory        m_dep  \
count    2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean     1238.518500     1.522250     4.309500    32.046500     0.501750   
std       439.418206     0.816004     4.341444    18.145715     0.288416   
min       501.000000     0.500000     0.000000     2.000000     0.100000   
25%       851.750000     0.700000     1.000000    16.000000     0.200000   
50%      1226.000000     1.500000     3.000000    32.000000     0.500000   
75%      1615.250000     2.200000     7.000000    48.000000     0.800000   
max      1998.000000     3.000000    19.000000    64.000000     1.000000   

         mobile_wt      n_cores           pc    px_height     px_width  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean    140.249000     4.520500     9.916500   645.108000  1251.515500   
std      35.399655     2.287837     6.064315   443.780811   432.199447   
min      80.000000     1.000000     0.000000     0.000000   500.000000   
25%     109.000000     3.000000     5.000000   282.750000   874.750000   
50%     141.000000     4.000000    10.000000   564.000000  1247.000000   
75%     170.000000     7.000000    15.000000   947.250000  1633.000000   
max     200.000000     8.000000    20.000000  1960.000000  1998.000000   

               ram         sc_h         sc_w    talk_time  price_range  
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  
mean   2124.213000    12.306500     5.767000    11.011000     1.500000  
std    1084.732044     4.213245     4.356398     5.463955     1.118314  
min     256.000000     5.000000     0.000000     2.000000     0.000000  
25%    1207.500000     9.000000     2.000000     6.000000     0.750000  
50%    2146.500000    12.000000     5.000000    11.000000     1.500000  
75%    3064.500000    16.000000     9.000000    16.000000     2.250000  
max    3998.000000    19.000000    18.000000    20.000000     3.000000

In [7]:
m.isnull().sum() # it will tells us about the missing values in the data

battery_power    0
clock_speed      0
fc               0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
price_range      0
dtype: int64

In [ ]:
# So after seeing the values we can say that there is no missing values in the data

In [8]:
m.dtypes

battery_power      int64
clock_speed      float64
fc                 int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
price_range        int64
dtype: object

In [33]:
for i in m.columns:
    print({i:m[i].unique()})

{'battery_power': array([ 842, 1021,  563, ..., 1139, 1467,  858], dtype=int64)}
{'clock_speed': array([2.2, 0.5, 2.5, 1.2, 1.7, 0.6, 2.9, 2.8, 2.1, 1. , 0.9, 1.1, 2.6,
       1.4, 1.6, 2.7, 1.3, 2.3, 2. , 1.8, 3. , 1.5, 1.9, 2.4, 0.8, 0.7])}
{'fc': array([ 1,  0,  2, 13,  3,  4,  5,  7, 11, 12, 16,  6, 15,  8,  9, 10, 18,
       17, 14, 19], dtype=int64)}
{'int_memory': array([ 7, 53, 41, 10, 44, 22, 24,  9, 33, 17, 52, 46, 13, 23, 49, 19, 39,
       47, 38,  8, 57, 51, 21,  5, 60, 61,  6, 11, 50, 34, 20, 27, 42, 40,
       64, 14, 63, 43, 16, 48, 12, 55, 36, 30, 45, 29, 58, 25,  3, 54, 15,
       37, 31, 32,  4, 18,  2, 56, 26, 35, 59, 28, 62], dtype=int64)}
{'m_dep': array([0.6, 0.7, 0.9, 0.8, 0.1, 0.5, 1. , 0.3, 0.4, 0.2])}
{'mobile_wt': array([188, 136, 145, 131, 141, 164, 139, 187, 174,  93, 182, 177, 159,
       198, 185, 196, 121, 101,  81, 156, 199, 114, 111, 132, 143,  96,
       200,  88, 150, 107, 100, 157, 160, 119,  87, 152, 166, 110, 118,
       162, 127, 109, 102, 104, 

In [ ]:
 #Price range --> 0(low cost), 1(medium cost), 2(high cost) and 3(very high cost).

In [9]:
# create X and Y  
X=m.values[:,0:-1]
Y=m.values[:,-1]

In [10]:
X.shape

(2000, 14)

In [11]:
Y.shape

(2000,)

In [12]:
Y=Y.astype(int)

In [13]:
from sklearn.preprocessing import StandardScaler  # HERE WE ARE SCALING THE DATA

scaler=StandardScaler()

scaler.fit(X)

X=scaler.transform(X)

In [14]:
from sklearn.model_selection import train_test_split
#split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=10)

In [15]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(1400, 14)
(600, 14)
(1400,)
(600,)


# KNN

In [16]:
# predicting using the Kneighbors_Classifier
from sklearn.neighbors import KNeighborsClassifier
model_knn= KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),metric='euclidean')
# euclidean,manhatten,minkowski
# fit the model on the data and predict the values
model_knn.fit(X_train,Y_train)

Y_pred=model_knn.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(3, 3), (3, 2), (2, 1), (3, 3), (1, 0), (3, 3), (3, 2), (3, 3), (1, 0), (3, 3), (2, 2), (3, 2), (0, 0), (1, 1), (0, 0), (3, 3), (2, 2), (3, 3), (2, 3), (2, 2), (3, 3), (2, 2), (0, 0), (1, 1), (0, 0), (0, 2), (3, 3), (3, 3), (1, 2), (1, 1), (2, 2), (0, 1), (3, 3), (2, 2), (2, 1), (2, 2), (1, 0), (1, 0), (2, 2), (0, 0), (3, 3), (2, 2), (2, 1), (0, 1), (1, 1), (3, 3), (1, 1), (0, 0), (1, 0), (2, 2), (1, 1), (3, 2), (2, 3), (3, 3), (2, 2), (3, 3), (2, 2), (3, 3), (0, 0), (0, 0), (1, 1), (1, 2), (0, 0), (0, 0), (2, 2), (0, 0), (2, 2), (1, 0), (1, 2), (3, 2), (2, 3), (2, 2), (1, 0), (1, 0), (3, 3), (2, 2), (3, 2), (3, 2), (2, 2), (1, 1), (3, 2), (0, 0), (1, 1), (0, 0), (0, 0), (3, 3), (2, 2), (3, 2), (3, 3), (3, 3), (2, 2), (3, 2), (3, 3), (3, 3), (3, 3), (1, 1), (0, 0), (1, 1), (0, 0), (1, 1), (3, 2), (0, 0), (1, 1), (2, 1), (1, 1), (3, 3), (2, 3), (1, 0), (2, 1), (2, 1), (2, 2), (0, 0), (3, 3), (1, 1), (2, 2), (1, 0), (1, 1), (2, 1), (3, 3), (0, 0), (1, 0), (0, 0), (3, 3), (2, 3), (1, 2),

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[119  20   1   0]
 [ 48  75  32   2]
 [  3  30  96  28]
 [  0   1  51  94]]
Classification report: 
              precision    recall  f1-score   support

           0       0.70      0.85      0.77       140
           1       0.60      0.48      0.53       157
           2       0.53      0.61      0.57       157
           3       0.76      0.64      0.70       146

    accuracy                           0.64       600
   macro avg       0.65      0.65      0.64       600
weighted avg       0.64      0.64      0.64       600

Accuracy of the model:  0.64


In [18]:
from sklearn.metrics import accuracy_score
my_dict={}
for k in range(1,31):
    model_knn=KNeighborsClassifier(n_neighbors=k,metric='euclidean')
    model_knn.fit(X_train,Y_train)
    Y_pred_1=model_knn.predict(X_test)
    print('Accuracy is',accuracy_score(Y_test,Y_pred_1),'for K value:',k)
    my_dict[k]=accuracy_score(Y_test,Y_pred_1)

Accuracy is 0.5383333333333333 for K value: 1
Accuracy is 0.495 for K value: 2
Accuracy is 0.5116666666666667 for K value: 3
Accuracy is 0.5516666666666666 for K value: 4
Accuracy is 0.57 for K value: 5
Accuracy is 0.5783333333333334 for K value: 6
Accuracy is 0.5783333333333334 for K value: 7
Accuracy is 0.5883333333333334 for K value: 8
Accuracy is 0.5966666666666667 for K value: 9
Accuracy is 0.5966666666666667 for K value: 10
Accuracy is 0.6166666666666667 for K value: 11
Accuracy is 0.6283333333333333 for K value: 12
Accuracy is 0.6316666666666667 for K value: 13
Accuracy is 0.6416666666666667 for K value: 14
Accuracy is 0.63 for K value: 15
Accuracy is 0.64 for K value: 16
Accuracy is 0.6566666666666666 for K value: 17
Accuracy is 0.6633333333333333 for K value: 18
Accuracy is 0.655 for K value: 19
Accuracy is 0.645 for K value: 20
Accuracy is 0.6516666666666666 for K value: 21
Accuracy is 0.65 for K value: 22
Accuracy is 0.6466666666666666 for K value: 23
Accuracy is 0.646666666

# LOGISTIC REGRESSION

In [19]:
from sklearn.linear_model import LogisticRegression
# create a model object
lm_class=LogisticRegression()
#train the model object
lm_class.fit(X_train,Y_train)

#print intercept and coefficients
print(lm_class.intercept_)
print(lm_class.coef_)

[-3.08359983  2.99836137  3.00094114 -2.91570269]
[[-2.61698341e+00  6.98204212e-02 -3.43451531e-02 -1.80799834e-01
   4.31384889e-02  3.70021994e-01 -2.10396230e-02 -9.71132538e-03
  -1.53401878e+00 -1.45129525e+00 -1.03428663e+01 -4.20987479e-02
   7.67651014e-02 -2.25297318e-02]
 [-8.42422967e-01 -3.92274306e-02  7.58172155e-04 -3.04019701e-02
   8.72657584e-02  1.37244383e-01 -9.43055062e-02 -1.41403352e-02
  -4.45972713e-01 -4.78580756e-01 -3.24968763e+00 -8.62032130e-02
  -1.90905497e-02 -2.19939034e-03]
 [ 7.85362158e-01  1.06329448e-02  2.41981333e-03 -1.24031969e-02
  -7.30574234e-02  9.81628625e-03  5.08516579e-02  3.60800088e-02
   4.50359811e-01  4.03713121e-01  3.25280846e+00 -5.65013473e-02
  -1.46726132e-02  1.75858316e-02]
 [ 2.67404422e+00 -4.12259355e-02  3.11671676e-02  2.23605001e-01
  -5.73468240e-02 -5.17082663e-01  6.44934713e-02 -1.22283483e-02
   1.52963168e+00  1.52616289e+00  1.03397455e+01  1.84803308e-01
  -4.30019385e-02  7.14329054e-03]]


In [20]:
# predict using the model
Y_pred=lm_class.predict(X_test)
print(Y_pred)

[3 3 2 3 1 3 3 3 1 3 2 3 0 1 0 3 2 3 2 2 3 2 0 1 0 0 2 3 1 1 2 0 3 2 2 2 1
 1 2 0 3 2 2 0 1 3 1 0 1 2 1 3 2 3 2 3 2 3 0 0 1 1 0 0 2 0 2 1 2 3 2 2 1 1
 3 1 3 3 2 1 3 0 0 0 0 3 2 3 3 3 2 3 3 3 3 1 0 1 0 1 3 0 1 1 1 3 2 1 2 2 2
 0 3 1 2 1 1 2 3 0 1 0 3 2 1 3 0 3 2 0 3 3 3 1 2 0 0 3 3 1 3 0 3 2 0 3 3 1
 2 0 1 0 0 1 1 1 0 0 2 1 1 2 3 2 2 2 0 1 1 1 3 3 3 2 0 2 3 2 2 2 1 2 2 2 3
 0 2 3 0 2 0 2 1 3 2 0 0 0 0 3 1 3 3 3 2 2 1 2 2 1 2 1 1 3 2 0 3 1 2 1 3 2
 0 3 0 1 2 2 1 0 1 1 0 3 0 1 0 2 0 3 1 2 0 1 1 2 2 3 0 3 2 1 0 3 2 1 2 1 0
 3 3 1 1 1 3 2 3 0 2 2 2 2 0 3 0 3 1 1 2 0 3 3 0 1 1 1 3 0 0 1 1 0 2 2 2 1
 2 0 0 3 1 3 2 2 1 0 1 1 2 1 0 1 1 2 2 0 0 0 3 3 0 1 0 2 0 0 2 1 2 3 1 1 1
 1 2 2 2 2 2 2 2 2 3 0 3 1 1 3 0 1 0 1 3 2 3 3 0 3 3 1 1 2 0 3 0 3 2 0 2 0
 0 3 0 1 2 2 0 3 0 0 3 2 0 0 0 3 1 3 3 1 0 1 0 3 3 3 1 0 2 1 0 3 0 3 2 2 1
 0 1 1 2 1 1 3 0 2 0 2 3 0 0 3 3 1 1 3 1 3 2 3 1 1 0 1 2 1 2 0 3 0 1 0 1 2
 2 0 2 1 1 0 1 0 0 2 0 1 1 2 2 0 0 1 3 0 1 0 3 2 3 1 0 3 1 0 3 2 3 2 3 0 3
 1 0 0 0 2 3 2 2 2 2 2 2 

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[140   0   0   0]
 [  4 152   1   0]
 [  0   5 150   2]
 [  0   0   3 143]]
Classification report: 
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       140
           1       0.97      0.97      0.97       157
           2       0.97      0.96      0.96       157
           3       0.99      0.98      0.98       146

    accuracy                           0.97       600
   macro avg       0.98      0.98      0.98       600
weighted avg       0.98      0.97      0.97       600

Accuracy of the model:  0.975


# SVC

In [22]:
from sklearn.model_selection import train_test_split
#split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=10)

In [23]:
from sklearn.svm import SVC
svc_model=SVC(kernel='rbf',C=1,gamma=0.1,probability=True)
svc_model.fit(X_train,Y_train)
Y_pred=svc_model.predict(X_test)
print(list(Y_pred))

[3, 3, 1, 3, 1, 3, 3, 3, 1, 3, 2, 3, 0, 1, 0, 3, 2, 3, 2, 2, 3, 2, 0, 1, 0, 0, 2, 3, 1, 1, 2, 0, 3, 2, 2, 2, 1, 0, 3, 0, 3, 2, 2, 0, 1, 3, 1, 0, 1, 1, 1, 2, 2, 3, 2, 3, 2, 3, 0, 0, 1, 2, 0, 0, 2, 0, 2, 1, 2, 3, 2, 2, 0, 1, 3, 1, 3, 3, 2, 1, 2, 0, 1, 0, 0, 3, 2, 2, 3, 3, 2, 3, 3, 3, 3, 2, 0, 1, 1, 1, 3, 0, 1, 2, 1, 3, 1, 1, 2, 1, 2, 0, 3, 1, 2, 1, 1, 1, 3, 0, 1, 0, 3, 2, 1, 3, 0, 3, 2, 0, 3, 2, 3, 1, 3, 0, 0, 2, 3, 1, 3, 0, 3, 2, 0, 3, 3, 1, 2, 0, 1, 0, 0, 1, 0, 1, 0, 0, 3, 1, 1, 1, 3, 2, 1, 2, 0, 1, 2, 1, 3, 3, 3, 2, 0, 2, 3, 2, 2, 2, 1, 2, 2, 2, 3, 0, 1, 3, 0, 3, 0, 2, 1, 3, 2, 0, 0, 0, 0, 3, 1, 3, 3, 3, 2, 2, 1, 2, 2, 1, 2, 1, 1, 3, 2, 1, 2, 1, 2, 1, 3, 2, 0, 3, 0, 1, 2, 2, 1, 0, 1, 1, 0, 3, 0, 1, 0, 2, 0, 3, 1, 2, 0, 1, 1, 2, 2, 3, 0, 2, 2, 1, 0, 3, 3, 1, 2, 1, 1, 3, 3, 1, 2, 2, 3, 2, 3, 0, 2, 2, 2, 2, 0, 3, 0, 3, 1, 2, 2, 0, 3, 3, 0, 1, 1, 1, 3, 0, 0, 1, 2, 0, 2, 3, 2, 0, 2, 0, 0, 3, 1, 3, 2, 2, 1, 0, 1, 2, 2, 1, 0, 1, 1, 2, 2, 0, 0, 0, 2, 3, 0, 1, 0, 2, 0, 1, 3, 1, 2, 3, 1, 1, 1, 

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[129  11   0   0]
 [  8 132  17   0]
 [  0  17 130  10]
 [  0   0  18 128]]
Classification report: 
              precision    recall  f1-score   support

           0       0.94      0.92      0.93       140
           1       0.82      0.84      0.83       157
           2       0.79      0.83      0.81       157
           3       0.93      0.88      0.90       146

    accuracy                           0.86       600
   macro avg       0.87      0.87      0.87       600
weighted avg       0.87      0.86      0.87       600

Accuracy of the model:  0.865


In [25]:
from sklearn import svm         # IT IS THE METHOD TO FIND OUT THE BEST HYPERPARAMETER VALUE FOR THE ALGORITHM

svc_model = svm.SVC(kernel="rbf")

parameter_space = {
    #'kernel': ["linear","rbf","poly","sigmoid"],
    'gamma': [0.1,0.01,0.001],
    "C": np.arange(0,101,5)
    #'C': [1,5,8,10,20,30, 40,50,70]
    
}
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svc_model, parameter_space, n_jobs=-1, cv=5)

In [26]:
clf.fit(X_train,Y_train)

GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'C': array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100]),
                         'gamma': [0.1, 0.01, 0.001]})

In [27]:
print('best parameter found:/n',clf.best_params_)

best parameter found:/n {'C': 100, 'gamma': 0.001}


In [28]:
from sklearn.svm import SVC
svc_model=SVC(kernel='rbf',C=100,gamma=0.001,probability=True)
svc_model.fit(X_train,Y_train)
Y_pred=svc_model.predict(X_test)
print(list(Y_pred))

[3, 3, 2, 3, 1, 3, 3, 3, 1, 3, 2, 3, 0, 1, 0, 3, 2, 3, 2, 2, 3, 2, 0, 1, 0, 0, 2, 3, 1, 1, 2, 0, 3, 2, 2, 2, 1, 1, 2, 0, 3, 2, 2, 0, 1, 3, 1, 0, 1, 2, 1, 3, 2, 3, 2, 3, 2, 3, 0, 0, 1, 1, 0, 0, 2, 0, 2, 0, 2, 3, 2, 2, 1, 1, 3, 1, 3, 3, 2, 1, 3, 0, 0, 0, 0, 3, 2, 3, 3, 3, 2, 3, 3, 3, 3, 1, 0, 1, 1, 1, 3, 0, 1, 1, 1, 3, 2, 1, 2, 2, 2, 0, 3, 1, 2, 1, 1, 1, 3, 0, 1, 0, 3, 2, 1, 3, 0, 3, 2, 0, 3, 3, 3, 1, 2, 0, 0, 3, 3, 1, 3, 0, 3, 2, 0, 3, 3, 1, 2, 0, 1, 0, 0, 1, 1, 1, 0, 0, 2, 1, 1, 2, 3, 2, 2, 2, 0, 1, 1, 1, 3, 3, 3, 2, 0, 2, 3, 2, 2, 2, 1, 2, 2, 2, 3, 0, 2, 3, 0, 2, 0, 2, 1, 3, 2, 0, 0, 0, 0, 3, 1, 3, 3, 3, 2, 2, 1, 2, 2, 1, 2, 1, 1, 3, 2, 1, 3, 1, 2, 1, 3, 2, 0, 3, 0, 1, 2, 2, 1, 0, 1, 1, 0, 3, 0, 1, 0, 2, 0, 3, 1, 2, 0, 1, 1, 2, 2, 3, 0, 3, 2, 1, 0, 3, 2, 1, 2, 1, 0, 3, 3, 1, 1, 1, 3, 2, 3, 0, 2, 2, 2, 2, 0, 3, 0, 3, 1, 1, 2, 0, 3, 3, 0, 1, 1, 1, 3, 0, 0, 1, 1, 0, 2, 3, 2, 1, 2, 0, 0, 3, 1, 3, 2, 2, 1, 0, 1, 2, 2, 1, 0, 1, 1, 2, 2, 0, 0, 0, 3, 3, 0, 1, 0, 2, 0, 0, 2, 1, 2, 3, 1, 1, 1, 

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[138   2   0   0]
 [  6 149   2   0]
 [  0   6 147   4]
 [  0   0   3 143]]
Classification report: 
              precision    recall  f1-score   support

           0       0.96      0.99      0.97       140
           1       0.95      0.95      0.95       157
           2       0.97      0.94      0.95       157
           3       0.97      0.98      0.98       146

    accuracy                           0.96       600
   macro avg       0.96      0.96      0.96       600
weighted avg       0.96      0.96      0.96       600

Accuracy of the model:  0.9616666666666667


# DT MODEL

In [30]:
from sklearn.model_selection import train_test_split
#split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=10)

In [31]:
from sklearn.tree import DecisionTreeClassifier
d_model=DecisionTreeClassifier(criterion='gini',random_state=10)
#min_sample_leaf,min_samples_split,max_depth,max_features [PRUNING HYPERPARAMETERS]
d_model.fit(X_train,Y_train)
Y_pred=d_model.predict(X_test)
print(list(Y_pred))

[3, 3, 1, 3, 1, 3, 3, 3, 1, 3, 3, 3, 0, 1, 0, 3, 2, 3, 2, 2, 3, 2, 0, 1, 0, 0, 2, 3, 1, 1, 2, 0, 3, 3, 2, 2, 1, 0, 2, 0, 3, 2, 2, 0, 1, 3, 1, 0, 1, 1, 1, 2, 2, 2, 3, 3, 2, 3, 0, 0, 1, 1, 0, 0, 3, 0, 2, 0, 2, 2, 2, 2, 0, 1, 3, 1, 3, 3, 2, 1, 3, 0, 1, 0, 0, 3, 2, 3, 3, 3, 1, 3, 3, 3, 3, 2, 0, 1, 1, 0, 3, 0, 1, 2, 1, 3, 2, 1, 2, 1, 2, 0, 3, 1, 2, 1, 1, 1, 3, 0, 1, 1, 3, 2, 1, 3, 0, 3, 2, 0, 3, 3, 3, 1, 3, 0, 0, 2, 3, 2, 3, 0, 3, 2, 0, 3, 2, 1, 2, 1, 1, 0, 0, 1, 0, 1, 0, 0, 3, 1, 1, 2, 3, 3, 2, 1, 1, 1, 2, 1, 3, 3, 3, 2, 0, 2, 3, 2, 2, 2, 1, 3, 1, 3, 3, 0, 1, 3, 0, 2, 1, 2, 1, 3, 2, 0, 0, 0, 0, 2, 0, 3, 3, 3, 2, 1, 1, 1, 2, 1, 2, 1, 1, 3, 2, 1, 3, 1, 3, 1, 3, 2, 0, 3, 0, 1, 2, 2, 1, 1, 1, 1, 0, 3, 0, 1, 0, 2, 0, 3, 1, 2, 0, 1, 1, 3, 2, 3, 0, 3, 2, 1, 0, 3, 2, 1, 2, 1, 1, 3, 3, 1, 2, 1, 3, 2, 3, 0, 2, 2, 3, 2, 0, 3, 0, 3, 1, 1, 3, 0, 3, 3, 0, 1, 1, 1, 3, 0, 0, 1, 1, 0, 2, 3, 2, 1, 2, 0, 0, 3, 1, 3, 2, 2, 1, 0, 1, 2, 2, 2, 0, 1, 1, 1, 2, 0, 0, 0, 3, 3, 0, 1, 0, 2, 0, 0, 2, 1, 2, 3, 1, 1, 1, 

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[128  12   0   0]
 [ 15 131  11   0]
 [  0  19 117  21]
 [  0   0  13 133]]
Classification report: 
              precision    recall  f1-score   support

           0       0.90      0.91      0.90       140
           1       0.81      0.83      0.82       157
           2       0.83      0.75      0.79       157
           3       0.86      0.91      0.89       146

    accuracy                           0.85       600
   macro avg       0.85      0.85      0.85       600
weighted avg       0.85      0.85      0.85       600

Accuracy of the model:  0.8483333333333334


SO AFTER APPLYING KNN,LOGISTIC REG,SVM AND D.T WE CAME TO KNOW THAT AMONG THIS FOUR LOGISTIC REGRESSION MODEL IS PROVIDING THE BEST ACCURACY AS WELL AS BEST RECALL VALUE SO FOR ANY UPCOMING FUTURE PREDICTIONS WE ARE GOING TO USE LOGISTIC REGRESSION MODEL.